spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  profiles:
    include: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    import:
        - optional:classpath:/value.yml
    
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace