name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Xcode
      run: |
        pod install --repo-update --clean-install --project-directory=CPR2U/
        xcodebuild build -workspace CPR2U/CPR2U.xcworkspace -scheme CPR2U-Workspace -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
