# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CPR2U' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CPR2U
use_frameworks!

pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']
source 'https://github.com/CocoaPods/Specs.git'
pod 'GoogleMaps'
pod 'GooglePlaces'

end
